#  ansible-playbook -i inventory  conditional.yaml 
---
- name: Content Playbook
  hosts: all
  user: ec2-user
  become: yes 
  become_method: sudo 
  gather_facts: yes 
  tasks:    
  - name: Add user bob  to amazon machine
    when: 
    - ansible_facts['distribution'] == "Amazon"
    - ansible_facts['distribution_version'] == "2"
    ansible.builtin.user:
      name: bob
      state: present
    ignore_errors: true


  # - name: Linux command
  #   command: |
  #   - tar  czvf   backup.tar.gz  /etc   /mnt 
  #   - tar  czvf   backup.tar.gz  /etc   /mnt 
  #   - tar  czvf   backup.tar.gz  /etc   /mnt 
  #   - tar  czvf   backup.tar.gz  /etc   /mnt 

  # - name: Another command 
  #   command: "{{ item }}"
  #   with_items:
  #   - tar  czvf   backup.tar.gz  /etc   /mnt 
  #   - tar  czvf   backup.tar.gz  /etc   /mnt 


  - name: Add user bob  to Ubuntu machine
    when: ansible_facts['distribution'] == "Ubuntu"
    ansible.builtin.group:
      name: sales
      state: present