#  ansible-playbook -i inventory  package.yaml 
---
- name: Package Playbook
  hosts: all
  user: ec2-user
  become: yes 
  become_method: sudo 
  tasks:
  - name: Install packages
    package: 
      name: "{{ item }}" 
      state: present    #absent    #installed     #latest
    with_items:
    - telnet 
    - elinks
    - lftp
    - httpd 











  - name: Add the user 'johnd' with a specific uid and a primary group of 'admin'
    ansible.builtin.user:
      name: "{{ item }}"
      group: wheel
      password: "$6$0VXbRW03$oBVeAYeYXyvCf5e3Qz7aqxAUAK/rJiUBjiBXh6S0Ofa5Mk8.ACsnnjNn9akhdxEFrO1ytuJ0wPpDZkXTxcQds."
    with_items:
    - john
    - lisa
    - bob
    - dan

  - name: Ensure group "sales" exists
    ansible.builtin.group:
      name: "{{ item }}"
      state: present
    with_items:
    - sales
    - marketing
    - billing