#  ansible-playbook -i inventory  first_playbook.yaml 
---
- name: Package Playbook
  hosts: all
  user: ec2-user
  become: yes 
  become_method: sudo 
  tasks:
  - name: Install telnet
    package: 
      name: telnet 
      state: present    #absent    #installed     #latest