#  ansible-playbook -i inventory  package.yaml 
---
- name: Package Playbook
  hosts: all
  user: ec2-user
  become: yes 
  become_method: sudo 
  tasks:
  - name: Install telnet
    package: 
      name: telnet 
      state: present    #absent    #installed     #latest

  - name: Add the user 'johnd' with a specific uid and a primary group of 'admin'
    ansible.builtin.user:
      name: johnd
      comment: John Doe
      uid: 1040
      group: wheel
      password: "$6$0VXbRW03$oBVeAYeYXyvCf5e3Qz7aqxAUAK/rJiUBjiBXh6S0Ofa5Mk8.ACsnnjNn9akhdxEFrO1ytuJ0wPpDZkXTxcQds."

  - name: Ensure group "sales" exists
    ansible.builtin.group:
      name: sales
      state: present