#  ansible-playbook  webserver.yaml 
---
- name: Content Playbook
  hosts: all
  user: ec2-user
  become: yes 
  become_method: sudo 
  tasks:    
  - name: Install webserver
    when: 
    - ansible_facts['distribution'] == "Amazon"
    - ansible_facts['distribution_version'] == "2"
    ansible.builtin.package:
      name: httpd
      state: present