#  ansible-playbook  webserver.yaml 
---
- name: Content Playbook
  hosts: all
  user: ec2-user
  become: yes 
  become_method: sudo 
  tasks:    
  - name: Install webserver and tools on amazon
    when: 
    - ansible_facts['distribution'] == "Amazon"
    - ansible_facts['distribution_version'] == "2"
    ansible.builtin.package:
      name: "{{ item }}"
      state: present
    with_items:
    - httpd
    - php
    - php-mysql
    - wget 
    notify: Amazon-Webserver



  - name: Download wordpress
    when: 
    - ansible_facts['distribution'] == "Amazon"
    - ansible_facts['distribution_version'] == "2"
    get_url:
      url: https://wordpress.org/wordpress-4.0.32.tar.gz
      dest: /tmp/wordpress-4.0.32.tar.gz
      mode: '0440'

  - name: Extract wordpress
    when: 
    - ansible_facts['distribution'] == "Amazon"
    - ansible_facts['distribution_version'] == "2"
    ansible.builtin.unarchive:
      src: /tmp/wordpress-4.0.32.tar.gz
      dest: /tmp/
      remote_src: true

  - name: Host Wordpress
    when: 
    - ansible_facts['distribution'] == "Amazon"
    - ansible_facts['distribution_version'] == "2"
    shell: "cp -rf /tmp/wordpress/* /var/www/html/"
    ignore_errors: true


  - name: Install webserver on ubuntu
    when: 
    - ansible_facts['distribution'] == "Ubuntu"
    - ansible_facts['distribution_version'] == "16.04"
    ansible.builtin.package:
      name: apache2
      state: present
    notify: Ubuntu-Webserver



  handlers:
    - name: Amazon-Webserver
      when: 
      - ansible_facts['distribution'] == "Amazon"
      - ansible_facts['distribution_version'] == "2"
      ansible.builtin.systemd:
        name: httpd
        state: restarted


    - name: Ubuntu-Webserver
      when: 
      - ansible_facts['distribution'] == "Ubuntu"
      - ansible_facts['distribution_version'] == "16.04"
      ansible.builtin.systemd:
        name: apache2
        state: restarted