#  ansible-playbook  webserver.yaml 
---
- name: Content Playbook
  hosts: all
  user: ec2-user
  become: yes 
  become_method: sudo 
  tasks:    
  - name: Install webserver on amazon
    when: 
    - ansible_facts['distribution'] == "Amazon"
    - ansible_facts['distribution_version'] == "2"
    ansible.builtin.package:
      name: httpd
      state: present
    notify: Amazon-Webserver

  - name: Install webserver on ubuntu
    when: 
    - ansible_facts['distribution'] == "Ubuntu"
    - ansible_facts['distribution_version'] == "16.04"
    ansible.builtin.package:
      name: apache2
      state: present
    notify: Ubuntu-Webserver




  handlers:
    - name: Amazon-Webserver
      when: 
      - ansible_facts['distribution'] == "Amazon"
      - ansible_facts['distribution_version'] == "2"
      ansible.builtin.systemd:
        name: httpd
        state: restarted


    - name: Ubuntu-Webserver
      when: 
      - ansible_facts['distribution'] == "Ubuntu"
      - ansible_facts['distribution_version'] == "16.04"
      ansible.builtin.systemd:
        name: apache2
        state: restarted