--- # ansible-playbook IAAC/ec2.yaml   --extra-vars "@IAAC/envs/virginia.yaml"
- name: Create ec2 
  hosts: localhost
  tasks:
  - name: EC
    amazon.aws.ec2:
      region: "{{ region }}"
      key_name: "{{ key_name }}"
      instance_type: "{{ instance_type }}"
      image: "{{ image }}"
      # assign_public_ip: false
      # vpc_subnet_id: subnet-03e9cab473ca995a4
      user_data: "sudo yum install httpd -y"
      instance_tags:
        Name: "{{ Name }}"