--- # ansible-playbook IAAC/ec2.yaml 
- name: Create ec2 
  hosts: localhost
  tasks:
  - name: EC
    amazon.aws.ec2:
      region: us-east-1
      key_name: laptop
      instance_type: t2.micro
      image: ami-0ab4d1e9cf9a1215a
      # assign_public_ip: false
      # vpc_subnet_id: subnet-03e9cab473ca995a4
      user_data: "sudo yum install httpd -y"
      instance_tags:
        Name: "Ansible"