--- # ansible-playbook IAAC/vpc.yaml   --extra-vars "@IAAC/envs/virginia.yaml"
- name: Create vpc 
  hosts: localhost
  vars_files:
    envs/dev.yaml
  tasks:
  - name: create a VPC
    amazon.aws.ec2_vpc_net:
      name: Ansible
      cidr_block: "{{ vpc_cidr_block }}"
      region: "{{ region }}"
      state: "{{ state }}"
      tags: "{{ aws_tags }}"
      tenancy: default
    register: Ansible

  - name: Get value 
    debug: 
      var: Ansible.vpc.id